In [1]:
import numpy as np
import pandas as pd

In [2]:
# Câu 1: Tạo DataFrame từ danh sách và áp dụng the series
def Giam(x):
    return -x if x < 500 else x - 1000

nganh = ['Kế toán', 'Ngoại ngữ', 'CNTT', 'Luật', 'VH-DL']
chitieu_tuyensinh = [300, 200, 400, 550, 800]
diemchuan = [18, 20, 22, 19, 21]

S = pd.Series(nganh)
C = pd.Series(chitieu_tuyensinh)
D = pd.Series(diemchuan)
df = pd.DataFrame({'Ngành': S, 'Chỉ tiêu tuyển sinh': C, 'Điểm chuẩn': D})
print("DataFrame ban đầu:")
print(df)
print("\n")
df['Chỉ tiêu tuyển sinh'] = df['Chỉ tiêu tuyển sinh'].apply(Giam)
print("DataFrame sau khi áp dụng hàm Giam:")
print(df)

DataFrame ban đầu:
       Ngành  Chỉ tiêu tuyển sinh  Điểm chuẩn
0    Kế toán                  300          18
1  Ngoại ngữ                  200          20
2       CNTT                  400          22
3       Luật                  550          19
4      VH-DL                  800          21


DataFrame sau khi áp dụng hàm Giam:
       Ngành  Chỉ tiêu tuyển sinh  Điểm chuẩn
0    Kế toán                 -300          18
1  Ngoại ngữ                 -200          20
2       CNTT                 -400          22
3       Luật                 -450          19
4      VH-DL                 -200          21

In [3]:
# Câu 2: Tạo DataFrame từ dictionary series
data = {
    "Họ tên" : pd.Series(['Nguyễn Văn A', 'Trần Thị B', 'Lê Văn C', 'Phạm Thị D', 'Hoàng Văn E']),
    "Điểm TB" : pd.Series([8.5, 7.0, 9.0, 6.5, 8.0])
}
df_students = pd.DataFrame(data)
print("\nDataFrame sinh viên:")
print(df_students)

DataFrame sinh viên:
         Họ tên  Điểm TB
0  Nguyễn Văn A      8.5
1    Trần Thị B      7.0
2      Lê Văn C      9.0
3    Phạm Thị D      6.5
4   Hoàng Văn E      8.0

In [4]:
# Câu 3: Tạo DataFrame từ NumPy ndArray
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
columns = ['A', 'B', 'C', 'D'][:arr.shape[1]]
df_array = pd.DataFrame(arr, columns=columns)
print("\nDataFrame từ mảng NumPy:")
print(df_array)

DataFrame từ mảng NumPy:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
# Câu 4: Tạo DataFrame và dùng sorting

df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
print("\nDataFrame ban đầu:")
print(df)
df.sort_index(axis = 1, ascending=False, inplace=True)
print("\nDataFrame sau khi sắp xếp theo chỉ số giảm dần:")
print(df)
df.sort_values(by='B', ascending=False, inplace=True)
print("\nDataFrame sau khi sắp xếp theo cột B giảm dần:")
print(df)

DataFrame ban đầu:
          A         B         C         D
0 -0.362056  0.266659  0.382320  0.406341
1  0.946685 -1.920414 -2.794624  1.773793
2  0.307185  0.242064  1.822237  1.564362
3 -0.811173 -1.206747 -0.186178 -1.241403
4 -1.038430 -0.743671  0.961521  1.610352
5  0.877943 -0.907515 -0.282617 -1.083584
6  0.353108  2.551892 -0.031434 -0.612386
7  0.092215  0.471480 -2.028185  0.602257
8  0.759087 -0.514024  0.078115 -0.482285
9  0.214964  0.718810 -1.366762  0.645609

DataFrame sau khi sắp xếp theo chỉ số giảm dần:
          D         C         B         A
0  0.406341  0.382320  0.266659 -0.362056
1  1.773793 -2.794624 -1.920414  0.946685
2  1.564362  1.822237  0.242064  0.307185
3 -1.241403 -0.186178 -1.206747 -0.811173
4  1.610352  0.961521 -0.743671 -1.038430
5 -1.083584 -0.282617 -0.907515  0.877943
6 -0.612386 -0.031434  2.551892  0.353108
7  0.602257 -2.028185  0.471480  0.092215
8 -0.482285  0.078115 -0.514024  0.759087
9  0.645609 -1.366762  0.718810  0.214964

DataFrame sau khi sắp xếp theo cột B giảm dần:
          D         C         B         A
6 -0.612386 -0.031434  2.551892  0.353108
9  0.645609 -1.366762  0.718810  0.214964
7  0.602257 -2.028185  0.471480  0.092215
0  0.406341  0.382320  0.266659 -0.362056
2  1.564362  1.822237  0.242064  0.307185
8 -0.482285  0.078115 -0.514024  0.759087
4  1.610352  0.961521 -0.743671 -1.038430
5 -1.083584 -0.282617 -0.907515  0.877943
3 -1.241403 -0.186178 -1.206747 -0.811173
1  1.773793 -2.794624 -1.920414  0.946685

In [6]:
# Câu 5: Select, Add, Delete, Insert, Assign columns
print("\nChọn cột A và B:")
print(df[['A', 'B']])

del df['D']
print("\nDataFrame sau khi xóa cột D:")
print(df)

third_col = df.pop('C')
print("\nDataFrame của cột C:")
print(third_col)

Chọn cột A và B:
          A         B
6  0.353108  2.551892
9  0.214964  0.718810
7  0.092215  0.471480
0 -0.362056  0.266659
2  0.307185  0.242064
8  0.759087 -0.514024
4 -1.038430 -0.743671
5  0.877943 -0.907515
3 -0.811173 -1.206747
1  0.946685 -1.920414

DataFrame sau khi xóa cột D:
          C         B         A
6 -0.031434  2.551892  0.353108
9 -1.366762  0.718810  0.214964
7 -2.028185  0.471480  0.092215
0  0.382320  0.266659 -0.362056
2  1.822237  0.242064  0.307185
8  0.078115 -0.514024  0.759087
4  0.961521 -0.743671 -1.038430
5 -0.282617 -0.907515  0.877943
3 -0.186178 -1.206747 -0.811173
1 -2.794624 -1.920414  0.946685

DataFrame của cột C:
6   -0.031434
9   -1.366762
7   -2.028185
0    0.382320
2    1.822237
8    0.078115
4    0.961521
5   -0.282617
3   -0.186178
1   -2.794624
Name: C, dtype: float64

In [7]:
df.insert(2, 'Q', third_col)
print("\nDataFrame sau khi chèn lại cột Q:")
print(df)

DataFrame sau khi chèn lại cột Q:
          B         A         Q
6  2.551892  0.353108 -0.031434
9  0.718810  0.214964 -1.366762
7  0.471480  0.092215 -2.028185
0  0.266659 -0.362056  0.382320
2  0.242064  0.307185  1.822237
8 -0.514024  0.759087  0.078115
4 -0.743671 -1.038430  0.961521
5 -0.907515  0.877943 -0.282617
3 -1.206747 -0.811173 -0.186178
1 -1.920414  0.946685 -2.794624

In [8]:
df = df.assign(E = df['A'] + df['B'], F = df['A'] - df['B'], G = df['A'] * df['B'], H = df['A'] / df['B'])
print("\nDataFrame sau khi thêm cột E, F, G và H:")
print(df)

DataFrame sau khi thêm cột E, F, G và H:
          B         A         Q         E         F         G         H
6  2.551892  0.353108 -0.031434  2.905000 -2.198784  0.901094  0.138371
9  0.718810  0.214964 -1.366762  0.933773 -0.503846  0.154518  0.299055
7  0.471480  0.092215 -2.028185  0.563695 -0.379265  0.043478  0.195586
0  0.266659 -0.362056  0.382320 -0.095397 -0.628715 -0.096546 -1.357749
2  0.242064  0.307185  1.822237  0.549249  0.065121  0.074358  1.269025
8 -0.514024  0.759087  0.078115  0.245063  1.273111 -0.390189 -1.476753
4 -0.743671 -1.038430  0.961521 -1.782101 -0.294759  0.772251  1.396356
5 -0.907515  0.877943 -0.282617 -0.029573  1.785458 -0.796747 -0.967414
3 -1.206747 -0.811173 -0.186178 -2.017920  0.395574  0.978880  0.672198
1 -1.920414  0.946685 -2.794624 -0.973729  2.867098 -1.818026 -0.492959

In [9]:
# Câu 6: Filter rows
filtered_df = df[df['A'] > 0]
print("\nDataFrame sau khi lọc các hàng có giá trị cột A > 0:")
print(filtered_df)

DataFrame sau khi lọc các hàng có giá trị cột A > 0:
          B         A         Q         E         F         G         H
6  2.551892  0.353108 -0.031434  2.905000 -2.198784  0.901094  0.138371
9  0.718810  0.214964 -1.366762  0.933773 -0.503846  0.154518  0.299055
7  0.471480  0.092215 -2.028185  0.563695 -0.379265  0.043478  0.195586
2  0.242064  0.307185  1.822237  0.549249  0.065121  0.074358  1.269025
8 -0.514024  0.759087  0.078115  0.245063  1.273111 -0.390189 -1.476753
5 -0.907515  0.877943 -0.282617 -0.029573  1.785458 -0.796747 -0.967414
1 -1.920414  0.946685 -2.794624 -0.973729  2.867098 -1.818026 -0.492959

In [10]:
# dùng loc và iloc
print("\nSử dụng loc:")
print(df.loc[filtered_df.index, ['A', 'B', 'E']])
print("\nSử dụng iloc:")
print(df.iloc[filtered_df.index, [0, 1, 3]])

Sử dụng loc:
          A         B         E
6  0.353108  2.551892  2.905000
9  0.214964  0.718810  0.933773
7  0.092215  0.471480  0.563695
2  0.307185  0.242064  0.549249
8  0.759087 -0.514024  0.245063
5  0.877943 -0.907515 -0.029573
1  0.946685 -1.920414 -0.973729

Sử dụng iloc:
          B         A         E
4 -0.743671 -1.038430 -1.782101
1 -1.920414  0.946685 -0.973729
5 -0.907515  0.877943 -0.029573
7  0.471480  0.092215  0.563695
3 -1.206747 -0.811173 -2.017920
8 -0.514024  0.759087  0.245063
9  0.718810  0.214964  0.933773

In [11]:
# Câu 7: Group by and Aggregate
data = {
    'Ngành': ['CNTT', 'CNTT', 'Kế toán', 'Kế toán', 'Luật', 'Luật'],
    'Điểm': [22, 24, 18, 20, 19, 21]
}
df = pd.DataFrame(data)
grouped = df.groupby('Ngành').agg({'Điểm': ['mean', 'max', 'min']})
print("\nBảng tổng hợp điểm theo ngành:")
print(grouped)

Bảng tổng hợp điểm theo ngành:
         Điểm
         mean max min
Ngành
CNTT     23.0  24  22
Kế toán  19.0  20  18
Luật     20.0  21  19

In [12]:
# Câu 8: Merge, Join, Concatenate
df1 = pd.DataFrame({
    'MSSV': [1, 2, 3],
    'Họ tên': ['Nguyễn Văn A', 'Trần Thị B', 'Lê Văn C']
})
df2 = pd.DataFrame({
    'MSSV': [1, 2, 4],
    'Điểm': [8, 9, 7]
})
merged_df = pd.merge(df1, df2, on='MSSV', how='inner')
print("\nDataFrame sau khi merge:")
print(merged_df)
concatenated_df = pd.concat([df1, df2], ignore_index=True, sort=False)
print("\nDataFrame sau khi concatenate:")
print(concatenated_df)

DataFrame sau khi merge:
   MSSV        Họ tên  Điểm
0     1  Nguyễn Văn A     8
1     2    Trần Thị B     9

DataFrame sau khi concatenate:
   MSSV        Họ tên  Điểm
0     1  Nguyễn Văn A   NaN
1     2    Trần Thị B   NaN
2     3      Lê Văn C   NaN
3     1           NaN   8.0
4     2           NaN   9.0
5     4           NaN   7.0

In [13]:
# Câu 9: Pivot tables
data = {
    'Ngành': ['CNTT', 'CNTT', 'Kế toán', 'Kế toán', 'Luật', 'Luật'],
    'Năm': [2022, 2023, 2022, 2023, 2022, 2023],
    'Chỉ tiêu': [400, 450, 300, 320, 500, 550]
}
df = pd.DataFrame(data)
pivot_table = df.pivot_table(values='Chỉ tiêu', index='Ngành', columns='Năm', aggfunc='sum', fill_value=0)
print("\nBảng pivot của chỉ tiêu theo ngành và năm:")
print(pivot_table)

Bảng pivot của chỉ tiêu theo ngành và năm:
Năm      2022  2023
Ngành
CNTT      400   450
Kế toán   300   320
Luật      500   550

In [14]:
# Câu 10: Đọc file CSV, Excel, JSON, HTML, SQL
# Đọc file CSV
df_csv1 = pd.read_csv('fifa19.csv', usecols=['Name', 'Age', 'Photo', 'Club'])
df_csv2 = pd.read_csv('weather.csv', usecols= ['pickup_datetime', 'wgustm', 'wgusti'])
print("\nĐọc file FIFA 2019:")
print(df_csv1.head())
print("\nĐọc file thời tiết:")
print(df_csv2.head())

Đọc file FIFA 2019:
                Name  Age                                           Photo  \
0           L. Messi   31  https://cdn.sofifa.org/players/4/19/158023.png
1  Cristiano Ronaldo   33   https://cdn.sofifa.org/players/4/19/20801.png
2          Neymar Jr   26  https://cdn.sofifa.org/players/4/19/190871.png
3             De Gea   27  https://cdn.sofifa.org/players/4/19/193080.png
4       K. De Bruyne   27  https://cdn.sofifa.org/players/4/19/192985.png

                  Club
0         FC Barcelona
1             Juventus
2  Paris Saint-Germain
3    Manchester United
4      Manchester City

Đọc file thời tiết:
       pickup_datetime      wgustm  wgusti
0  2015-12-31 00:15:00  Light Rain    rain
1  2015-12-31 00:42:00    Overcast  cloudy
2  2015-12-31 00:51:00    Overcast  cloudy
3  2015-12-31 01:51:00    Overcast  cloudy
4  2015-12-31 02:51:00    Overcast  cloudy

In [19]:
from IPython.display import display

# Đọc file Excel
df_excel = pd.read_excel('khach_hang.xlsx')
print("\nĐọc file khách hàng từ Excel:")
# Hiển thị đẹp hơn với pandas, có thể dùng display hoặc style
display(df_excel.head())

Đọc file khách hàng từ Excel:

   MaKH         HoTen  SoDienThoai   DiaChi
0  KH01  Nguyen Van A    909123456   TP.HCM
1  KH02    Tran Thi B    911222333   Ha Noi
2  KH03      Le Van C    988777666  Da Nang

In [17]:
from IPython.display import display

# Đọc file JSON
data = pd.read_json("provinces.json")

# Lấy phần 'provinces' (danh sách tỉnh/thành)
df_json = pd.DataFrame(data["provinces"].tolist())

print("\nĐọc file tỉnh thành từ JSON:")
display(df_json[["code", "name"]].head())

Đọc file tỉnh thành từ JSON:

  code              name
0   01  Thành phố Hà Nội
1   04     Tỉnh Cao Bằng
2   08  Tỉnh Tuyên Quang
3   11    Tỉnh Điện Biên
4   12     Tỉnh Lai Châu